# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Historische Kampfkunst Lintfort
email: MSK@ltv-1927.de
description: >-2 # this ('>-2') means to ignore newlines until "baseurl:", requiring an intent of 2 spaces
  Sport mit historischem Hintergrund 
  - mit dem 'Langen Schwert',  
  mit anderen bewaffneten, sowie waffenlosen Techniken.
  Unterstützt durch Erkenntnisse aus dem modernen Breitensport.
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hema-ltv1927.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: account ID
#github_username:  account ID

# Fields used by the theme but not defaulted with the Jekyll new command.
# Default author for everything on this side as it is only me.
# author: Peter Joost
# Social media links to the accounts as below here
# youtube_username: account ID
# instagram_username: account ID
#linkedin_username: account ID
#github_username: account ID

# New fields, not used by default by Jekyll and themes - these required changes to the original minima theme!
# Copyright, copyright symbol and year (auto)
copyright: "LTV 1927 e.V."
# Extra favicon for the page
favicon: ./assets/favicon.ico
# the main logo of the page
title-logo: ./assets/title-logo.png
# Below change would allow to use a logo from an online source, requires also change in the header.html
# title-logo: https://avatars.githubusercontent.com/u/5503293?s=96&v=4

# Build settings
# removed minima theme as it is now a regular page, now longer using a gem-based theme
# so not connected to any updates of the original minima theme.
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
